
running 3 tests
test test_features ... ok
test test_types ... ok
(memory.fill
 (i32.const 2048)
 (i32.const 1024)
 (i32.const 12)
)
test test_core ... FAILED

failures:

---- test_core stdout ----
func_names = [
    "kitchen()sinker",
]
segments = ["hello, world", "im passive"]
thread 'test_core' panicked at 'assertion failed: module.validate()', src/main.rs:574:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_core

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

